server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # Rutea automaticamente por nombre de servicio: /MENU-SERVICE/**
          enabled: true
          lower-case-service-id: true
      routes:
        # menu-service: platos
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/menu/**
        # order-service: pedidos
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/pedidos/**
        # report-service: reportes y analitica
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/reportes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
